export const State = {
	ended: false,
	won: false,
	paused: false,
	then: Date.now(),
	soundtrack: null,
	gameWon: null,
	gameLost: null,
	timer: 30,
	frameCount: 0,
	keys: {},
	score: 0,
	area: 0,
	maxEnemies: 5,
	addEnemy: () => {},
	removeEnemy: () => {},
	addPoints: () => {},
};
