export const State = {
	paused: false,
	ended: false,
	won: false,
	lost: false,
	keys: {},
	score: 0,
	area: 0,
	minEnemies: 2,
	maxEnemies: 6,
	addEnemy: () => {},
	removeEnemy: () => {},
	addScore: () => {},
	addEnemyScore: () => {},
	onPlayerCut: () => {},
	onPlayerReset: () => {},
};
